environment:
  global:
    PROJECT_NAME: sqlite-build
  matrix:
    #########################################################################
    # x86 vs140
    ##########################################################################
    # with xp support
    - TARGET: i686-pc-windows-msvc14_xp
      ARCH: x86
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      TOOLSET: v140
      ESCRIPT: v140_xp.bat
    # without xp support
    - TARGET: i686-pc-windows-msvc14
      ARCH: x86
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      TOOLSET: v140

    #########################################################################
    # x64 vs140
    ##########################################################################
    # with xp support
    - TARGET: x86_64-pc-windows-msvc14_xp
      ARCH: x64
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      TOOLSET: v140
      ESCRIPT: v140_xp64.bat
    # without xp support
    - TARGET: x86_64-pc-windows-msvc14
      ARCH: x64
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      TOOLSET: v140

    #########################################################################
    # x86 vs120
    ##########################################################################
    # with xp support
    - TARGET: i686-pc-windows-msvc12_xp
      ARCH: x86
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      TOOLSET: v120
      ESCRIPT: v120_xp.bat
    # without xp support
    - TARGET: i686-pc-windows-msvc12
      ARCH: x86
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      TOOLSET: v120

    #########################################################################
    # x64 vs120
    ##########################################################################
    # with xp support
    - TARGET: x86_64-pc-windows-msvc12_xp
      ARCH: x64
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      TOOLSET: v120
      ESCRIPT: v120_xp64.bat
    # without xp support
    - TARGET: x86_64-pc-windows-msvc12
      ARCH: x64
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      TOOLSET: v120

install:
  - if defined VS call "%VS%" %ARCH%
  - if defined ESCRIPT call "%ESCRIPT%"

build: false

build_script:
  - release.cmd

before_deploy:
  - cd dist-%TARGET%
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Sqlite Build for Windows'
  artifact: /.*\.zip/
  auth_token:
    secure: cW2lNuSBqYoZhkWPcNmD/QQ5gyvXu7oM0etZqA9hvnu/BqRSWgDuiKvYWrGsHPIZ
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
